[package]
name = "mysoc_validator_core"
version = "0.1.0"
edition = "2021"

[dependencies]
fuzzy_date = { path = "../fuzzy_date" }
popolo_validator = { path = "../popolo_validator" }
pyo3 = { version = "0.22.2" , features = ["abi3-py39"] }