[package]
name = "popolo_validator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
serde_derive = "1.0.203"
serde_json = "1.0.118"
fuzzy_date = { path = "../fuzzy_date" }
pyo3 = { version = "0.22.2" }
itertools = "0.13.0"
lazy_static = "1.5.0"
regex = "1.11.0"
